backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown"}
          - label: 'Cats'
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string"}
              - { label: "Description", name: "description", widget: "text"}
      - label: "Main"
        name: "main"
        file: "content/main.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Subtitle", name: "subtitle", widget: "string"}
          - { label: "BackgroundImage", name: "backgroundImage", widget: "image"}
          - { label: "OpeningTitle", name: "openingTitle", widget: "string"}
          - { label: "OpeningDescription", name: "openingDescription", widget: "text"}
          - label: 'Carousel'
            name: "carousel"
            widget: list
            fields:
              - { label: "Image", name: "image", widget: "image"}
          - { label: "AboutUsTitle", name: "aboutUsTitle", widget: "string"}
          - { label: "AboutUsDescription", name: "aboutUsDescription", widget: "text"}
      - label: "RepairPhone"
        name: "repairPhone"
        file: "content/repair-phone.md"
        fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Subtitle", name: "subtitle", widget: "string"}
            - { label: "BackgroundImage", name: "backgroundImage", widget: "image"}
            - { label: "BrandTitle", name: "brandTitle", widget: "string"}
            - label: 'Brands'
              name: "brands"
              widget: list
              fields:
                - { label: "BrandImage", name: "brandImage", widget: "image"}
                - { label: "BrandName", name: "brandName", widget: "string"}
                - { label: "BrandUrl", name: "brandUrl", widget: "string"}
      - label: "RepairPhoneApple"
        name: "repairPhoneApple"
        file: "content/repair-phone-apple.md"
        fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Subtitle", name: "subtitle", widget: "string"}
            - { label: "BackgroundImage", name: "backgroundImage", widget: "image"}
            - { label: "PhoneAppleTitle", name: "phoneAppleTitle", widget: "string"}
            - label: 'Products'
              name: "products"
              widget: list
              fields:
                - { label: "AppleProductImage", name: "appleProductImage", widget: "image"}
                - { label: "AppleProductName", name: "appleProductName", widget: "string"}
                - { label: "AppleProductDescription", name: "appleProductDescription", widget: "text"}
                - { label: "AppleProductYear", name: "appleProductYear", widget: "datetime", default: "", date_format: "YYYY"}
                - { label: "AppleProductUrl", name: "appleProductUrl", widget: "string"}          